### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by jdustinlewis**
Added instructions to install prerequisites for alpine (especially in Docker)

### CODE REVIEW

**Comment by jdustinlewis** [comment]
This is my first pull request, let me know if I should do anything differently.
As an aside, thanks for putting together this great script! I've been using VirtualBox to download files since moving to Mojave and it's a huge pain. This script will let me offload it to my Raspberry Pi instead, which also cuts some steps out of my workflow.

**Comment by jdustinlewis** [comment]
I intend to write a dockerfile soon, which is why I was working on the alpine prerequisites.

**Comment by jdustinlewis** [comment]
Dockerfile added, with instructions.

**Comment by chbrown** [comment]
Hiya! Sorry for neglecting this — I appreciate the interest, and I just used your `apk add` command in d350dd1 👍 ... so it wasn't all for naught 😉  

My hesitancy is because it feels like a lot of overhead / complexity to support a single bash script, and since a lot of users are coming from a background of _never_ having opened up a command line, I want to keep it as simple as possible for the majority of users.

I'm not adverse to Dockerization if that makes things easier for some users, and I like the notion of your Raspberry Pi project :) But Docker seems like a lot of extra work when IMHO it doesn't seem that onerous or unusual to install a few (pretty normal!) packages 🤷‍♂️  — you have to clone the repo, build the docker image, ensure that image is available wherever you're going to run it, and then run it with a linked volume because the whole point is to download files.

Here's a workflow / PR that I _would_ consider, if possible:
1. Add a `Dockerfile` to the repo.
2. Create a GitHub Action to build the docker image and push it to my Docker Hub (free) account
   - Presumably, if somebody trusts my GitHub repos, they'll trust my Docker Hub repos
   - Though I'm not sure if Docker Hub's recent policy change ("Starting November 1, 2020: Free accounts may retain inactive images for up to 6 months") impacts the reliability of this approach
   - I'm not super familiar with GitHub Actions so maybe this isn't trivial / free?
3. Add a short section to the README documenting the `docker run chbrown/overdrive ...` call that would replace the `overdrive ...` call for `docker` users.

**Comment by jdustinlewis** [comment]
You're right, there's a deal of overhead to doing it in Docker, and the prerequisites to run it natively are really not asking very much.

Building the image is one thing, but what has gotten me away from using Docker myself is managing the interaction between the container and the files. I set up an alias to shorten the command, but handling the cli syntax gets muddy.

If I get time, I'll dig into Github Actions and see if that can be usable.

Until then, I'm good with closing this PR. Thanks for the feedback!

**Pull request closed without merging**
